[package]
name = "zerolaunch-rs"
version = "0.4.5"
description = "ðŸš€ Lightning-fast, accurate, lightweight & pure Windows application launcher!"
authors = ["ghost-him"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "zerolaunch_rs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "^2", features = [] }

[dependencies]
windows = { version = "0.60.0", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Management_Deployment",
    "Win32_System_Threading",
    "Foundation",
    "Win32_Security",
    "Foundation_Collections",
    "System",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_UI_Shell",
    "Storage_Streams",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_System_Variant",
    "Win32_System_Registry",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
    "Win32_System_Diagnostics",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_Graphics_Dwm",
    "Win32_UI_Controls",
] }

tauri = { version = "^2", features = ["tray-icon", "image-ico", "image-png"] }
tauri-plugin-shell = "2"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
lazy_static = "^1.5.0"
rdev = { version = "^0.5.3", features = ["unstable_grab"] }
widestring = "^1.2.0"
windows-core = "^0.59.0"
rayon = "^1.10.0"
base64 = "^0.22.1"
dashmap = "^6.1.0"
image = "^0.25.5"
tracing = "^0.1.41"
tracing-subscriber = { version = "^0.3.19", features = ["env-filter"] }
tracing-appender = "^0.2.3"
chrono = "^0.4.40"
parking_lot = "^0.12.3"
tauri-plugin-global-shortcut = "^2.2.0"
tauri-plugin-dialog = { version = "^2.2.0" }
timer = "^0.2.0"
backtrace = "^0.3.74"
tauri-plugin-notification = "^2"
kmeans_colors = "^0.6.0"
palette = "^0.7.6"
rand = "^0.9.0"
anyhow = "1.0.97"
reqwest = { version = "0.12.14", features = ["json"] }
lnk = "0.5.1"
async-trait = "0.1.88"
tokio = { version = "1.44.1", features = ["full"] }
reqwest_dav = "0.1.14"
onedrive-api = "0.10.2"
tauri-plugin-deep-link = "2"
winreg = "0.55.0"
tauri-utils = { version = "2.2.0", features = ["schema"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "^2"
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
